# 実行するプレイブックを指定。

- name: webserverのミドルウェアをインストールする
  hosts: localhost
  become: yes
  connection: local
  roles:
    - httpd

- name: システムユーザを作成する
  hosts: localhost
  vars_files:
    - vars/main.yml
  become: yes
  connection: local
  roles:
    - sysuser

- name: サーバにphpと周辺環境をインストールする
  hosts: localhost
  become: yes
  connection: local
  roles:
    - php

