# 実行するプレイブックを指定。

- name: webserverのミドルウェアをインストールする
  hosts: localhost
  become: yes
  connection: local
  roles:
    - httpd

- name: システムユーザを作成する
  hosts: localhost
  vars_files:
    - vars/main.yml
  become: yes
  connection: local
  roles:
    - sysuser

- name: システムユーザにphpと周辺環境をインストールする
  hosts: localhost
  vars_files:
    - vars/main.yml
  become: yes
  become_user: "{{ production_system_user }}"
  connection: local
  roles:
    - php

- name: システムユーザにphpと周辺環境をインストールする
  hosts: localhost
  vars_files:
    - vars/main.yml
  become: yes
  become_user: "{{ staging_system_user }}"
  connection: local
  roles:
    - php
