# 実行するプレイブックを指定。

- name: vagrantユーザにphpenvをインストールする
  hosts: localhost
  vars_files:
    - vars/vagrant.yml
  become: yes
  become_user: "{{ user_name }}"
  connection: local
  roles:
    - phpenv

- name: vagrantユーザにrbenvをインストールする
  hosts: localhost
  vars_files:
    - vars/vagrant.yml
  become: yes
  become_user: "{{ user_name }}"
  connection: local
  roles:
    - rbenv

- name: vagrantユーザにpyenvをインストールする
  hosts: localhost
  vars_files:
    - vars/vagrant.yml
  become: yes
  become_user: "{{ user_name }}"
  connection: local
  roles:
    - pyenv

- name: vagrantユーザにnode.js & yarnをインストールする
  hosts: localhost
  vars_files:
    - vars/vagrant.yml
  become: yes
  become_user: "{{ user_name }}"
  connection: local
  roles:
    - nodejs
