- name: Httpdインストール
  yum: name=httpd state=latest
  tags:
    - yum
- name: Httpd起動
  systemd: name=httpd state=started enabled=yes
- name: Httpdの起動確認
  shell: ps aux | grep httpd
  register: ps_result
  changed_when: false
- debug: var=ps_result.stdout_lines
  when: ps_result | success
